export const cpComponentLight = {
  c_accordionBasic_spacing_itemGap_titleSection_default: "8px",
  c_accordionBasic_spacing_itemGap_foldedContents_comfortable: "8px",
  c_accordionBasic_spacing_itemGap_foldedContents_loose: "16px",
  c_accordionBasic_spacing_itemGap_foldedContents_compact: "4px",
  c_accordionContainer_color_background_ghost: "#ffffff00",
  c_accordionContainer_color_background_surface: "#5a657616",
  c_accordionContainer_color_background_background: "#fff",
  c_accordionContainer_color_border_ghost: "#5a657725",
  c_accordionContainer_color_border_surface: "#5a657725",
  c_accordionContainer_color_border_background: "#5a657725",
  c_accordionContainer_borderWidth_borderTrue: "1px",
  c_accordionContainer_borderWidth_borderFalse: "0px",
  c_accordionContainer_spacing_padding_none_S_horizontalPadding: "0px",
  c_accordionContainer_spacing_padding_none_S_verticalPadding: "8px",
  c_accordionContainer_spacing_padding_none_M_horizontalPadding: "0px",
  c_accordionContainer_spacing_padding_none_M_verticalPadding: "10px",
  c_accordionContainer_spacing_padding_none_L_horizontalPadding: "0px",
  c_accordionContainer_spacing_padding_none_L_verticalPadding: "12px",
  c_accordionContainer_spacing_padding_none_XL_horizontalPadding: "0px",
  c_accordionContainer_spacing_padding_none_XL_verticalPadding: "16px",
  c_accordionContainer_spacing_padding_S_S_horizontalPadding: "12px",
  c_accordionContainer_spacing_padding_S_S_verticalPadding: "8px",
  c_accordionContainer_spacing_padding_S_M_horizontalPadding: "12px",
  c_accordionContainer_spacing_padding_S_M_verticalPadding: "10px",
  c_accordionContainer_spacing_padding_S_L_horizontalPadding: "12px",
  c_accordionContainer_spacing_padding_S_L_verticalPadding: "12px",
  c_accordionContainer_spacing_padding_S_XL_horizontalPadding: "12px",
  c_accordionContainer_spacing_padding_S_XL_verticalPadding: "16px",
  c_accordionContainer_spacing_padding_M_S_horizontalPadding: "16px",
  c_accordionContainer_spacing_padding_M_S_verticalPadding: "8px",
  c_accordionContainer_spacing_padding_M_M_horizontalPadding: "16px",
  c_accordionContainer_spacing_padding_M_M_verticalPadding: "10px",
  c_accordionContainer_spacing_padding_M_L_horizontalPadding: "16px",
  c_accordionContainer_spacing_padding_M_L_verticalPadding: "12px",
  c_accordionContainer_spacing_padding_M_XL_horizontalPadding: "16px",
  c_accordionContainer_spacing_padding_M_XL_verticalPadding: "16px",
  c_accordionContainer_spacing_padding_L_S_horizontalPadding: "20px",
  c_accordionContainer_spacing_padding_L_S_verticalPadding: "8px",
  c_accordionContainer_spacing_padding_L_M_horizontalPadding: "20px",
  c_accordionContainer_spacing_padding_L_M_verticalPadding: "10px",
  c_accordionContainer_spacing_padding_L_L_horizontalPadding: "20px",
  c_accordionContainer_spacing_padding_L_L_verticalPadding: "12px",
  c_accordionContainer_spacing_padding_L_XL_horizontalPadding: "20px",
  c_accordionContainer_spacing_padding_L_XL_verticalPadding: "16px",
  c_accordionContainer_radius: "8px",
  c_dotIndicatorItem_size_S: "8px",
  c_dotIndicatorItem_size_M: "10px",
  c_dotIndicatorItem_color_background_active_black_default: "#000000",
  c_dotIndicatorItem_color_background_active_black_light: "#000000b3",
  c_dotIndicatorItem_color_background_active_white_default: "#ffffff",
  c_dotIndicatorItem_color_background_active_white_light: "#ffffffb3",
  c_dotIndicatorItem_color_background_active_primary_default: "#26C7D9",
  c_dotIndicatorItem_color_background_active_primary_light: "#26C7D9",
  c_dotIndicatorItem_color_background_active_neutral_default: "#16181de6",
  c_dotIndicatorItem_color_background_active_neutral_light: "#444e5c86",
  c_dotIndicatorItem_color_background_inactive_black_default: "#00000033",
  c_dotIndicatorItem_color_background_inactive_black_light: "#0000001a",
  c_dotIndicatorItem_color_background_inactive_white_default: "#ffffff80",
  c_dotIndicatorItem_color_background_inactive_white_light: "#ffffff33",
  c_dotIndicatorItem_color_background_inactive_primary_default: "#444e5c55",
  c_dotIndicatorItem_color_background_inactive_primary_light: "#5a657725",
  c_dotIndicatorItem_color_background_inactive_neutral_default: "#444e5c55",
  c_dotIndicatorItem_color_background_inactive_neutral_light: "#5a657725",
  c_dotIndicatorItem_color_border_active_black_default: "#ffffff33",
  c_dotIndicatorItem_color_border_active_black_light: "#ffffff33",
  c_dotIndicatorItem_color_border_active_white_default: "#0000001a",
  c_dotIndicatorItem_color_border_active_white_light: "#0000001a",
  c_dotIndicatorItem_color_border_active_primary_default: "#ffffff1a",
  c_dotIndicatorItem_color_border_active_primary_light: "#ffffff1a",
  c_dotIndicatorItem_color_border_active_neutral_default: "#ffffff1a",
  c_dotIndicatorItem_color_border_active_neutral_light: "#ffffff1a",
  c_dotIndicatorItem_color_border_inactive_black_default: "#ffffff33",
  c_dotIndicatorItem_color_border_inactive_black_light: "#ffffff33",
  c_dotIndicatorItem_color_border_inactive_white_default: "#0000001a",
  c_dotIndicatorItem_color_border_inactive_white_light: "#0000001a",
  c_dotIndicatorItem_color_border_inactive_primary_default: "#ffffff1a",
  c_dotIndicatorItem_color_border_inactive_primary_light: "#ffffff1a",
  c_dotIndicatorItem_color_border_inactive_neutral_default: "#ffffff1a",
  c_dotIndicatorItem_color_border_inactive_neutral_light: "#ffffff1a",
  c_dotIndicatorItem_borderWidth_S: "1px",
  c_dotIndicatorItem_borderWidth_M: "1px",
  c_dotIndicatorItem_radius: "50%",
  c_dotIndicator_spacing_itemGap_comfortable_S: "6px",
  c_dotIndicator_spacing_itemGap_comfortable_M: "6px",
  c_dotIndicator_spacing_itemGap_compact_S: "4px",
  c_dotIndicator_spacing_itemGap_compact_M: "4px",
  c_dotIndicator_spacing_itemGap_loose_S: "8px",
  c_dotIndicator_spacing_itemGap_loose_M: "8px",
  c_carouselNavigationArea_size_width_S: "24px",
  c_carouselNavigationArea_size_width_M: "32px",
  c_carouselNavigationArea_color_background_background_left:
    "linear-gradient(90deg, #ffffff 0%, #ffffff00 100%)",
  c_carouselNavigationArea_color_background_background_right:
    "linear-gradient(270deg, #ffffff 0%, #ffffff00 100%)",
  c_carouselNavigationArea_color_background_none_left:
    "linear-gradient(90deg, #ffffff00 0%, #ffffff00 100%)",
  c_carouselNavigationArea_color_background_none_right:
    "linear-gradient(270deg, #ffffff00 0%, #ffffff00 100%)",
  c_carouselNavigationArea_color_background_elevationFirst_left:
    "linear-gradient(90deg, #ffffff 0%, #ffffff00 100%)",
  c_carouselNavigationArea_color_background_elevationFirst_right:
    "linear-gradient(270deg, #ffffff 0%, #ffffff00 100%)",
  c_carouselNavigationArea_color_background_elevationSecond_left:
    "linear-gradient(90deg, #ffffff 0%, #ffffff00 100%)",
  c_carouselNavigationArea_color_background_elevationSecond_right:
    "linear-gradient(270deg, #ffffff 0%, #ffffff00 100%)",
  c_carouselNavigationArea_color_base_background_startColor: "#ffffff",
  c_carouselNavigationArea_color_base_background_endColor: "#ffffff00",
  c_carouselNavigationArea_color_base_none_startColor: "#ffffff00",
  c_carouselNavigationArea_color_base_none_endColor: "#ffffff00",
  c_carouselNavigationArea_color_base_elevationFirst_startColor: "#ffffff",
  c_carouselNavigationArea_color_base_elevationFirst_endColor: "#ffffff00",
  c_carouselNavigationArea_color_base_elevationSecond_startColor: "#ffffff",
  c_carouselNavigationArea_color_base_elevationSecond_endColor: "#ffffff00",
  c_complexMenuContents_spacing_itemGap_loose: "16px",
  c_complexMenuContents_spacing_itemGap_comfortable: "12px",
  c_complexMenuContents_spacing_itemGap_compact: "8px",
  c_complexMenuContents_spacing_padding_none_none: "0px",
  c_complexMenuContents_spacing_padding_none_XS: "4px 0px",
  c_complexMenuContents_spacing_padding_none_S: "8px 0px",
  c_complexMenuContents_spacing_padding_none_M: "12px 0px",
  c_complexMenuContents_spacing_padding_none_L: "16px 0px",
  c_complexMenuContents_spacing_padding_S_none: "0px 8px",
  c_complexMenuContents_spacing_padding_S_XS: "4px 8px",
  c_complexMenuContents_spacing_padding_S_S: "8px",
  c_complexMenuContents_spacing_padding_S_M: "12px 8px",
  c_complexMenuContents_spacing_padding_S_L: "16px 8px",
  c_complexMenuContents_spacing_padding_M_none: "0px 12px",
  c_complexMenuContents_spacing_padding_M_XS: "4px 12px",
  c_complexMenuContents_spacing_padding_M_S: "8px 12px",
  c_complexMenuContents_spacing_padding_M_M: "12px",
  c_complexMenuContents_spacing_padding_M_L: "16px 12px",
  c_complexMenuContents_spacing_padding_L_none: "0px 16px",
  c_complexMenuContents_spacing_padding_L_XS: "4px 16px",
  c_complexMenuContents_spacing_padding_L_S: "8px 16px",
  c_complexMenuContents_spacing_padding_L_M: "12px 16px",
  c_complexMenuContents_spacing_padding_L_L: "16px",
  c_complexMenuRightItem_spacing_padding_none: "0px",
  c_complexMenuRightItem_spacing_padding_right: "0px 8px 0px 0px",
  c_complexMenuRightItem_spacing_padding_left: "0px 0px 0px 8px",
  c_complexMenuRightItem_spacing_itemGap: "8px",
  c_complexMenuLeftItem_spacing_padding_none: "0px",
  c_complexMenuLeftItem_spacing_padding_right: "0px 8px 0px 0px",
  c_complexMenuLeftItem_spacing_padding_left: "0px 0px 0px 8px",
  c_complexMenuLeftItem_spacing_itemGap: "8px",
  c_complexMenuContainer_color_background_borderFalse_none_default: "#ffffff00",
  c_complexMenuContainer_color_background_borderFalse_none_hover: "#5a657616",
  c_complexMenuContainer_color_background_borderFalse_none_selected:
    "#26c7d91a",
  c_complexMenuContainer_color_background_borderFalse_surface_default:
    "#5a657616",
  c_complexMenuContainer_color_background_borderFalse_surface_hover:
    "#5a657725",
  c_complexMenuContainer_color_background_borderFalse_surface_selected:
    "#26c7d91a",
  c_complexMenuContainer_color_background_borderFalse_background_default:
    "#fff",
  c_complexMenuContainer_color_background_borderFalse_background_hover:
    "#f1f2f4",
  c_complexMenuContainer_color_background_borderFalse_background_selected:
    "#e9f9fb",
  c_complexMenuContainer_color_background_borderTrue_none_default: "#ffffff00",
  c_complexMenuContainer_color_background_borderTrue_none_hover: "#ffffff00",
  c_complexMenuContainer_color_background_borderTrue_none_selected: "#ffffff00",
  c_complexMenuContainer_color_background_borderTrue_surface_default:
    "#5a657616",
  c_complexMenuContainer_color_background_borderTrue_surface_hover: "#5a657616",
  c_complexMenuContainer_color_background_borderTrue_surface_selected:
    "#5a657616",
  c_complexMenuContainer_color_background_borderTrue_background_default: "#fff",
  c_complexMenuContainer_color_background_borderTrue_background_hover: "#fff",
  c_complexMenuContainer_color_background_borderTrue_background_selected:
    "#fff",
  c_complexMenuContainer_color_border_default: "#5a657725",
  c_complexMenuContainer_color_border_hover: "#5a65773d",
  c_complexMenuContainer_color_border_selected: "#26C7D9",
  c_complexMenuContainer_borderWidth_borderFalse_default: "0px",
  c_complexMenuContainer_borderWidth_borderTrue_default: "1px",
  c_complexMenuContainer_borderWidth_borderTrue_hover: "1px",
  c_complexMenuContainer_borderWidth_borderTrue_selected: "1px",
  c_complexMenuContainer_height_minHeight_S: "32px",
  c_complexMenuContainer_height_minHeight_M: "40px",
  c_complexMenuContainer_radius_M: "8px",
  c_complexMenuContainer_opacity_disabled: "0.5",
  c_container_padding_none: "0px",
  c_container_padding_S: "8px",
  c_container_padding_SM: "12px",
  c_container_padding_M: "16px",
  c_container_padding_ML: "20px",
  c_container_padding_L: "24px",
  c_containerSwapArea_padding_none_none_none: "0px",
  c_containerSwapArea_padding_none_none_S: "0px 0px 8px 0px",
  c_containerSwapArea_padding_none_none_SM: "0px 0px 12px 0px",
  c_containerSwapArea_padding_none_none_M: "0px 0px 16px 0px",
  c_containerSwapArea_padding_none_none_ML: "0px 0px 20px 0px",
  c_containerSwapArea_padding_none_none_L: "0px 0px 24px 0px",
  c_containerSwapArea_padding_none_S_none: "8px 0px 0px 0px",
  c_containerSwapArea_padding_none_S_S: "8px 0px",
  c_containerSwapArea_padding_none_S_SM: "8px 0px 12px 0px",
  c_containerSwapArea_padding_none_S_M: "8px 0px 16px 0px",
  c_containerSwapArea_padding_none_S_ML: "8px 0px 20px 0px",
  c_containerSwapArea_padding_none_S_L: "8px 0px 24px 0px",
  c_containerSwapArea_padding_none_SM_none: "12px 0px 0px 0px",
  c_containerSwapArea_padding_none_SM_S: "12px 0px 8px 0px",
  c_containerSwapArea_padding_none_SM_SM: "12px 0px",
  c_containerSwapArea_padding_none_SM_M: "12px 0px 16px 0px",
  c_containerSwapArea_padding_none_SM_ML: "12px 0px 20px 0px",
  c_containerSwapArea_padding_none_SM_L: "12px 0px 24px 0px",
  c_containerSwapArea_padding_none_M_none: "16px 0px 0px 0px",
  c_containerSwapArea_padding_none_M_S: "16px 0px 8px 0px",
  c_containerSwapArea_padding_none_M_SM: "16px 0px 12px 0px",
  c_containerSwapArea_padding_none_M_M: "16px 0px",
  c_containerSwapArea_padding_none_M_ML: "16px 0px 20px 0px",
  c_containerSwapArea_padding_none_M_L: "16px 0px 24px 0px",
  c_containerSwapArea_padding_none_ML_none: "20px 0px 0px 0px",
  c_containerSwapArea_padding_none_ML_S: "20px 0px 8px 0px",
  c_containerSwapArea_padding_none_ML_SM: "20px 0px 12px 0px",
  c_containerSwapArea_padding_none_ML_M: "20px 0px 16px 0px",
  c_containerSwapArea_padding_none_ML_ML: "20px 0px",
  c_containerSwapArea_padding_none_ML_L: "20px 0px 24px 0px",
  c_containerSwapArea_padding_none_L_none: "24px 0px 0px 0px",
  c_containerSwapArea_padding_none_L_S: "24px 0px 8px 0px",
  c_containerSwapArea_padding_none_L_SM: "24px 0px 12px 0px",
  c_containerSwapArea_padding_none_L_M: "24px 0px 16px 0px",
  c_containerSwapArea_padding_none_L_ML: "24px 0px 20px 0px",
  c_containerSwapArea_padding_none_L_L: "24px 0px",
  c_containerSwapArea_padding_S_none_none: "0px 8px",
  c_containerSwapArea_padding_S_none_S: "0px 8px 8px 8px",
  c_containerSwapArea_padding_S_none_SM: "0px 8px 12px 8px",
  c_containerSwapArea_padding_S_none_M: "0px 8px 16px 8px",
  c_containerSwapArea_padding_S_none_ML: "0px 8px 20px 8px",
  c_containerSwapArea_padding_S_none_L: "0px 8px 24px 8px",
  c_containerSwapArea_padding_S_S_none: "8px 8px 0px 8px",
  c_containerSwapArea_padding_S_S_S: "8px",
  c_containerSwapArea_padding_S_S_SM: "8px 8px 12px 8px",
  c_containerSwapArea_padding_S_S_M: "8px 8px 16px 8px",
  c_containerSwapArea_padding_S_S_ML: "8px 8px 20px 8px",
  c_containerSwapArea_padding_S_S_L: "8px 8px 24px 8px",
  c_containerSwapArea_padding_S_SM_none: "12px 8px 0px 8px",
  c_containerSwapArea_padding_S_SM_S: "12px 8px 8px 8px",
  c_containerSwapArea_padding_S_SM_SM: "12px 8px",
  c_containerSwapArea_padding_S_SM_M: "12px 8px 16px 8px",
  c_containerSwapArea_padding_S_SM_ML: "12px 8px 20px 8px",
  c_containerSwapArea_padding_S_SM_L: "12px 8px 24px 8px",
  c_containerSwapArea_padding_S_M_none: "16px 8px 0px 8px",
  c_containerSwapArea_padding_S_M_S: "16px 8px 8px 8px",
  c_containerSwapArea_padding_S_M_SM: "16px 8px 12px 8px",
  c_containerSwapArea_padding_S_M_M: "16px 8px",
  c_containerSwapArea_padding_S_M_ML: "16px 8px 20px 8px",
  c_containerSwapArea_padding_S_M_L: "16px 8px 24px 8px",
  c_containerSwapArea_padding_S_ML_none: "20px 8px 0px 8px",
  c_containerSwapArea_padding_S_ML_S: "20px 8px 8px 8px",
  c_containerSwapArea_padding_S_ML_SM: "20px 8px 12px 8px",
  c_containerSwapArea_padding_S_ML_M: "20px 8px 16px 8px",
  c_containerSwapArea_padding_S_ML_ML: "20px 8px",
  c_containerSwapArea_padding_S_ML_L: "20px 8px 24px 8px",
  c_containerSwapArea_padding_S_L_none: "24px 8px 0px 8px",
  c_containerSwapArea_padding_S_L_S: "24px 8px 8px 8px",
  c_containerSwapArea_padding_S_L_SM: "24px 8px 12px 8px",
  c_containerSwapArea_padding_S_L_M: "24px 8px 16px 8px",
  c_containerSwapArea_padding_S_L_ML: "24px 8px 20px 8px",
  c_containerSwapArea_padding_S_L_L: "24px 8px",
  c_containerSwapArea_padding_SM_none_none: "0px 12px",
  c_containerSwapArea_padding_SM_none_S: "0px 12px 8px 12px",
  c_containerSwapArea_padding_SM_none_SM: "0px 12px 12px 12px",
  c_containerSwapArea_padding_SM_none_M: "0px 12px 16px 12px",
  c_containerSwapArea_padding_SM_none_ML: "0px 12px 20px 12px",
  c_containerSwapArea_padding_SM_none_L: "0px 12px 24px 12px",
  c_containerSwapArea_padding_SM_S_none: "8px 12px 0px 12px",
  c_containerSwapArea_padding_SM_S_S: "8px 12px",
  c_containerSwapArea_padding_SM_S_SM: "8px 12px 12px 12px",
  c_containerSwapArea_padding_SM_S_M: "8px 12px 16px 12px",
  c_containerSwapArea_padding_SM_S_ML: "8px 12px 20px 12px",
  c_containerSwapArea_padding_SM_S_L: "8px 12px 24px 12px",
  c_containerSwapArea_padding_SM_SM_none: "12px 12px 0px 12px",
  c_containerSwapArea_padding_SM_SM_S: "12px 12px 8px 12px",
  c_containerSwapArea_padding_SM_SM_SM: "12px",
  c_containerSwapArea_padding_SM_SM_M: "12px 12px 16px 12px",
  c_containerSwapArea_padding_SM_SM_ML: "12px 12px 20px 12px",
  c_containerSwapArea_padding_SM_SM_L: "12px 12px 24px 12px",
  c_containerSwapArea_padding_SM_M_none: "16px 12px 0px 12px",
  c_containerSwapArea_padding_SM_M_S: "16px 12px 8px 12px",
  c_containerSwapArea_padding_SM_M_SM: "16px 12px 12px 12px",
  c_containerSwapArea_padding_SM_M_M: "16px 12px",
  c_containerSwapArea_padding_SM_M_ML: "16px 12px 20px 12px",
  c_containerSwapArea_padding_SM_M_L: "16px 12px 24px 12px",
  c_containerSwapArea_padding_SM_ML_none: "20px 12px 0px 12px",
  c_containerSwapArea_padding_SM_ML_S: "20px 12px 8px 12px",
  c_containerSwapArea_padding_SM_ML_SM: "20px 12px 12px 12px",
  c_containerSwapArea_padding_SM_ML_M: "20px 12px 16px 12px",
  c_containerSwapArea_padding_SM_ML_ML: "20px 12px",
  c_containerSwapArea_padding_SM_ML_L: "20px 12px 24px 12px",
  c_containerSwapArea_padding_SM_L_none: "24px 12px 0px 12px",
  c_containerSwapArea_padding_SM_L_S: "24px 12px 8px 12px",
  c_containerSwapArea_padding_SM_L_SM: "24px 12px 12px 12px",
  c_containerSwapArea_padding_SM_L_M: "24px 12px 16px 12px",
  c_containerSwapArea_padding_SM_L_ML: "24px 12px 20px 12px",
  c_containerSwapArea_padding_SM_L_L: "24px 12px",
  c_containerSwapArea_padding_M_none_none: "0px 16px",
  c_containerSwapArea_padding_M_none_S: "0px 16px 8px 16px",
  c_containerSwapArea_padding_M_none_SM: "0px 16px 12px 16px",
  c_containerSwapArea_padding_M_none_M: "0px 16px 16px 16px",
  c_containerSwapArea_padding_M_none_ML: "0px 16px 20px 16px",
  c_containerSwapArea_padding_M_none_L: "0px 16px 24px 16px",
  c_containerSwapArea_padding_M_S_none: "8px 16px 0px 16px",
  c_containerSwapArea_padding_M_S_S: "8px 16px",
  c_containerSwapArea_padding_M_S_SM: "8px 16px 12px 16px",
  c_containerSwapArea_padding_M_S_M: "8px 16px 16px 16px",
  c_containerSwapArea_padding_M_S_ML: "8px 16px 20px 16px",
  c_containerSwapArea_padding_M_S_L: "8px 16px 24px 16px",
  c_containerSwapArea_padding_M_SM_none: "12px 16px 0px 16px",
  c_containerSwapArea_padding_M_SM_S: "12px 16px 8px 16px",
  c_containerSwapArea_padding_M_SM_SM: "12px 16px",
  c_containerSwapArea_padding_M_SM_M: "12px 16px 16px 16px",
  c_containerSwapArea_padding_M_SM_ML: "12px 16px 20px 16px",
  c_containerSwapArea_padding_M_SM_L: "12px 16px 24px 16px",
  c_containerSwapArea_padding_M_M_none: "16px 16px 0px 16px",
  c_containerSwapArea_padding_M_M_S: "16px 16px 8px 16px",
  c_containerSwapArea_padding_M_M_SM: "16px 16px 12px 16px",
  c_containerSwapArea_padding_M_M_M: "16px",
  c_containerSwapArea_padding_M_M_ML: "16px 16px 20px 16px",
  c_containerSwapArea_padding_M_M_L: "16px 16px 24px 16px",
  c_containerSwapArea_padding_M_ML_none: "20px 16px 0px 16px",
  c_containerSwapArea_padding_M_ML_S: "20px 16px 8px 16px",
  c_containerSwapArea_padding_M_ML_SM: "20px 16px 12px 16px",
  c_containerSwapArea_padding_M_ML_M: "20px 16px 16px 16px",
  c_containerSwapArea_padding_M_ML_ML: "20px 16px",
  c_containerSwapArea_padding_M_ML_L: "20px 16px 24px 16px",
  c_containerSwapArea_padding_M_L_none: "24px 16px 0px 16px",
  c_containerSwapArea_padding_M_L_S: "24px 16px 8px 16px",
  c_containerSwapArea_padding_M_L_SM: "24px 16px 12px 16px",
  c_containerSwapArea_padding_M_L_M: "24px 16px 16px 16px",
  c_containerSwapArea_padding_M_L_ML: "24px 16px 20px 16px",
  c_containerSwapArea_padding_M_L_L: "24px 16px",
  c_containerSwapArea_padding_ML_none_none: "0px 20px",
  c_containerSwapArea_padding_ML_none_S: "0px 20px 8px 20px",
  c_containerSwapArea_padding_ML_none_SM: "0px 20px 12px 20px",
  c_containerSwapArea_padding_ML_none_M: "0px 20px 16px 20px",
  c_containerSwapArea_padding_ML_none_ML: "0px 20px 20px 20px",
  c_containerSwapArea_padding_ML_none_L: "0px 20px 24px 20px",
  c_containerSwapArea_padding_ML_S_none: "8px 20px 0px 20px",
  c_containerSwapArea_padding_ML_S_S: "8px 20px",
  c_containerSwapArea_padding_ML_S_SM: "8px 20px 12px 20px",
  c_containerSwapArea_padding_ML_S_M: "8px 20px 16px 20px",
  c_containerSwapArea_padding_ML_S_ML: "8px 20px 20px 20px",
  c_containerSwapArea_padding_ML_S_L: "8px 20px 24px 20px",
  c_containerSwapArea_padding_ML_SM_none: "12px 20px 0px 20px",
  c_containerSwapArea_padding_ML_SM_S: "12px 20px 8px 20px",
  c_containerSwapArea_padding_ML_SM_SM: "12px 20px",
  c_containerSwapArea_padding_ML_SM_M: "12px 20px 16px 20px",
  c_containerSwapArea_padding_ML_SM_ML: "12px 20px 20px 20px",
  c_containerSwapArea_padding_ML_SM_L: "12px 20px 24px 20px",
  c_containerSwapArea_padding_ML_M_none: "16px 20px 0px 20px",
  c_containerSwapArea_padding_ML_M_S: "16px 20px 8px 20px",
  c_containerSwapArea_padding_ML_M_SM: "16px 20px 12px 20px",
  c_containerSwapArea_padding_ML_M_M: "16px 20px",
  c_containerSwapArea_padding_ML_M_ML: "16px 20px 20px 20px",
  c_containerSwapArea_padding_ML_M_L: "16px 20px 24px 20px",
  c_containerSwapArea_padding_ML_ML_none: "20px 20px 0px 20px",
  c_containerSwapArea_padding_ML_ML_S: "20px 20px 8px 20px",
  c_containerSwapArea_padding_ML_ML_SM: "20px 20px 12px 20px",
  c_containerSwapArea_padding_ML_ML_M: "20px 20px 16px 20px",
  c_containerSwapArea_padding_ML_ML_ML: "20px",
  c_containerSwapArea_padding_ML_ML_L: "20px 20px 24px 20px",
  c_containerSwapArea_padding_ML_L_none: "24px 20px 0px 20px",
  c_containerSwapArea_padding_ML_L_S: "24px 20px 8px 20px",
  c_containerSwapArea_padding_ML_L_SM: "24px 20px 12px 20px",
  c_containerSwapArea_padding_ML_L_M: "24px 20px 16px 20px",
  c_containerSwapArea_padding_ML_L_ML: "24px 20px 20px 20px",
  c_containerSwapArea_padding_ML_L_L: "24px 20px",
  c_containerSwapArea_padding_L_none_none: "0px 24px",
  c_containerSwapArea_padding_L_none_S: "0px 24px 8px 24px",
  c_containerSwapArea_padding_L_none_SM: "0px 24px 12px 24px",
  c_containerSwapArea_padding_L_none_M: "0px 24px 16px 24px",
  c_containerSwapArea_padding_L_none_ML: "0px 24px 20px 24px",
  c_containerSwapArea_padding_L_none_L: "0px 24px 24px 24px",
  c_containerSwapArea_padding_L_S_none: "8px 24px 0px 24px",
  c_containerSwapArea_padding_L_S_S: "8px 24px",
  c_containerSwapArea_padding_L_S_SM: "8px 24px 12px 24px",
  c_containerSwapArea_padding_L_S_M: "8px 24px 16px 24px",
  c_containerSwapArea_padding_L_S_ML: "8px 24px 20px 24px",
  c_containerSwapArea_padding_L_S_L: "8px 24px 24px 24px",
  c_containerSwapArea_padding_L_SM_none: "12px 24px 0px 24px",
  c_containerSwapArea_padding_L_SM_S: "12px 24px 8px 24px",
  c_containerSwapArea_padding_L_SM_SM: "12px 24px",
  c_containerSwapArea_padding_L_SM_M: "12px 24px 16px 24px",
  c_containerSwapArea_padding_L_SM_ML: "12px 24px 20px 24px",
  c_containerSwapArea_padding_L_SM_L: "12px 24px 24px 24px",
  c_containerSwapArea_padding_L_M_none: "16px 24px 0px 24px",
  c_containerSwapArea_padding_L_M_S: "16px 24px 8px 24px",
  c_containerSwapArea_padding_L_M_SM: "16px 24px 12px 24px",
  c_containerSwapArea_padding_L_M_M: "16px 24px",
  c_containerSwapArea_padding_L_M_ML: "16px 24px 20px 24px",
  c_containerSwapArea_padding_L_M_L: "16px 24px 24px 24px",
  c_containerSwapArea_padding_L_ML_none: "20px 24px 0px 24px",
  c_containerSwapArea_padding_L_ML_S: "20px 24px 8px 24px",
  c_containerSwapArea_padding_L_ML_SM: "20px 24px 12px 24px",
  c_containerSwapArea_padding_L_ML_M: "20px 24px 16px 24px",
  c_containerSwapArea_padding_L_ML_ML: "20px 24px",
  c_containerSwapArea_padding_L_ML_L: "20px 24px 24px 24px",
  c_containerSwapArea_padding_L_L_none: "24px 24px 0px 24px",
  c_containerSwapArea_padding_L_L_S: "24px 24px 8px 24px",
  c_containerSwapArea_padding_L_L_SM: "24px 24px 12px 24px",
  c_containerSwapArea_padding_L_L_M: "24px 24px 16px 24px",
  c_containerSwapArea_padding_L_L_ML: "24px 24px 20px 24px",
  c_containerSwapArea_padding_L_L_L: "24px",
  c_popoverContainer_color_background_first: "#fff",
  c_popoverContainer_color_background_second: "#fff",
  c_popoverContainer_radius_default: "16px",
  c_popoverContainer_shadow_default: "0px 6px 20px 0 rgba(0, 0, 0, 0.2)",
  c_panelContinaner_color_background_default: "#fff",
  c_panelContinaner_color_border_sideDivider: "#5a657725",
  c_galleryItemBasic_spacing_itemGap_comfortable: "8px",
  c_galleryItemBasic_spacing_itemGap_loose: "12px",
  c_galleryItemBasic_spacing_itemGap_compact: "4px",
  c_graphicItem_size_container_3XS: "40px",
  c_graphicItem_size_container_2XS: "48px",
  c_graphicItem_size_container_XS: "56px",
  c_graphicItem_size_container_S: "64px",
  c_graphicItem_size_container_M: "80px",
  c_graphicItem_size_image_3XS: "28px",
  c_graphicItem_size_image_2XS: "36px",
  c_graphicItem_size_image_XS: "40px",
  c_graphicItem_size_image_S: "48px",
  c_graphicItem_size_image_M: "56px",
  c_graphicItem_color_background_none: "#ffffff00",
  c_graphicItem_color_background_surface: "#5a657616",
  c_graphicItem_color_background_background: "#fff",
  c_graphicItem_color_border_default: "#5a65773d",
  c_graphicItem_borderWidth: "1px",
  c_graphicItem_radius_3XS: "8px",
  c_graphicItem_radius_2XS: "8px",
  c_graphicItem_radius_XS: "8px",
  c_graphicItem_radius_S: "10px",
  c_graphicItem_radius_M: "12px",
  c_graphicMenu_color_background_none_borderTrue_hover: "#ffffff00",
  c_graphicMenu_color_background_none_borderTrue_selected: "#ffffff00",
  c_graphicMenu_color_background_none_borderFalse_hover: "#5a657616",
  c_graphicMenu_color_background_none_borderFalse_selected: "#26c7d91a",
  c_graphicMenu_color_background_surface_borderTrue_hover: "#5a657616",
  c_graphicMenu_color_background_surface_borderTrue_selected: "#5a657616",
  c_graphicMenu_color_background_surface_borderFalse_hover: "#5a657616",
  c_graphicMenu_color_background_surface_borderFalse_selected: "#26c7d91a",
  c_graphicMenu_color_background_background_borderTrue_hover: "#fff",
  c_graphicMenu_color_background_background_borderTrue_selected: "#fff",
  c_graphicMenu_color_background_background_borderFalse_hover: "#f1f2f4",
  c_graphicMenu_color_background_background_borderFalse_selected: "#e9f9fb",
  c_graphicMenu_color_border_none_borderTrue_hover: "#5a65773d",
  c_graphicMenu_color_border_none_borderTrue_selected: "#26C7D9",
  c_graphicMenu_color_border_none_borderFalse_hover: "#ffffff00",
  c_graphicMenu_color_border_none_borderFalse_selected: "#ffffff00",
  c_graphicMenu_color_border_surface_borderTrue_hover: "#5a65773d",
  c_graphicMenu_color_border_surface_borderTrue_selected: "#26C7D9",
  c_graphicMenu_color_border_surface_borderFalse_hover: "#ffffff00",
  c_graphicMenu_color_border_surface_borderFalse_selected: "#ffffff00",
  c_graphicMenu_color_border_background_borderTrue_hover: "#5a65773d",
  c_graphicMenu_color_border_background_borderTrue_selected: "#26C7D9",
  c_graphicMenu_color_border_background_borderFalse_hover: "#ffffff00",
  c_graphicMenu_color_border_background_borderFalse_selected: "#ffffff00",
  c_graphicMenu_color_borderWidth_borderTrue_hover: "2px",
  c_graphicMenu_color_borderWidth_borderTrue_selected: "2px",
  c_graphicMenu_color_contents_label_hover: "#16181d",
  c_graphicMenu_color_contents_label_selected: "#21afbf",
  c_graphicMenu_spacing_itemGap_compact: "4px",
  c_graphicMenu_spacing_itemGap_comfortable: "8px",
  c_contentsGridStandard_spacing_itemGap_column_XS: "10px",
  c_contentsGridStandard_spacing_itemGap_column_S: "16px",
  c_contentsGridStandard_spacing_itemGap_column_M: "24px",
  c_contentsGridStandard_spacing_itemGap_column_L: "32px",
  c_contentsGridStandard_spacing_itemGap_row_XS: "10px",
  c_contentsGridStandard_spacing_itemGap_row_S: "16px",
  c_contentsGridStandard_spacing_itemGap_row_M: "24px",
  c_contentsGridStandard_spacing_itemGap_row_L: "32px",
  c_contentsWrap_spacing_itemGap_column_XS: "10px",
  c_contentsWrap_spacing_itemGap_column_S: "16px",
  c_contentsWrap_spacing_itemGap_column_M: "24px",
  c_contentsWrap_spacing_itemGap_column_L: "32px",
  c_contentsWrap_spacing_itemGap_row_XS: "10px",
  c_contentsWrap_spacing_itemGap_row_S: "16px",
  c_contentsWrap_spacing_itemGap_row_M: "24px",
  c_contentsWrap_spacing_itemGap_row_L: "32px",
  c_contentsItemList_spacing_itemGap_XS: "10px",
  c_contentsItemList_spacing_itemGap_S: "16px",
  c_contentsItemList_spacing_itemGap_M: "24px",
  c_contentsItemList_spacing_itemGap_L: "32px",
  c_imageListAreaQuiltedBasic_spacing_itemGap_S: "8px",
  c_imageListAreaQuiltedBasic_spacing_itemGap_M: "16px",
  c_headerContentsBasic_typography_S:
    "600 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_headerContentsBasic_typography_M:
    "600 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_headerContentsBasic_typography_L:
    "600 1.25rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_headerContentsBasic_typography_2XL:
    "600 1.75rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_headerContentsBasic_color_contents_text: "#16181d",
  c_headerContentsBasic_spacing_itemGap_cancel: "4px",
  c_headerContentsBasic_spacing_itemGap_rightItem: "8px",
  c_headerContentsBasic_spacing_itemGap_endItem: "16px",
  c_iconBasic_color_contents_neutralDeep: "#16181d",
  c_iconBasic_color_contents_neutralLight: "#70798f",
  c_iconBasic_color_contents_neutralDeepInverse: "#fffffff2",
  c_iconBasic_color_contents_neutralLightInverse: "#ffffff80",
  c_iconBasic_color_contents_primary: "#26C7D9",
  c_iconBasic_color_contents_black: "#000000",
  c_iconBasic_color_contents_white: "#ffffff",
  c_iconBasic_color_contents_green: "#40BF8B",
  c_iconBasic_color_contents_yellow: "#F5D70A",
  c_iconBasic_color_contents_red: "#e3371c",
  c_iconBasic_color_contents_purple: "#935cd6",
  c_iconBasic_color_contents_blue: "#1A7BE5",
  c_iconBasic_size_contents_XS: "16px",
  c_iconBasic_size_contents_S: "20px",
  c_iconBasic_size_contents_M: "24px",
  c_iconBasic_size_contents_ML: "28px",
  c_iconBasic_size_contents_L: "32px",
  c_iconBasic_size_contents_XL: "40px",
  c_infoList_spacing_padding_none_M: "0px",
  c_infoList_spacing_padding_surface_M: "16px",
  c_infoList_spacing_padding_background_M: "16px",
  c_infoList_spacing_itemGap_M: "8px",
  c_infoList_color_background_none: "#ffffff00",
  c_infoList_color_background_surface: "#5a657616",
  c_infoList_color_background_background: "#fff",
  c_infoList_color_border_none: "#ffffff00",
  c_infoList_color_border_surface: "#5a657725",
  c_infoList_color_border_background: "#5a657725",
  c_infoList_radius_M: "8px",
  c_infoList_borderWidth_borderTrue: "1px",
  c_infoList_borderWidth_borderFalse: "0px",
  c_labelSection_spacing_itemGap_M: "8px",
  c_ratingItem_color_contents_active_primary: "#26C7D9",
  c_ratingItem_color_contents_inactive_primary: "#444e5c55",
  c_ratingItem_size_contents_S: "16px",
  c_ratingItem_size_contents_M: "20px",
  c_rating_spacing_itemGap_S_comfortable: "0px",
  c_rating_spacing_itemGap_S_compact: "-2px",
  c_rating_spacing_itemGap_S_loose: "2px",
  c_rating_spacing_itemGap_M_comfortable: "0px",
  c_rating_spacing_itemGap_M_compact: "-2px",
  c_rating_spacing_itemGap_M_loose: "2px",
  c_brandLogo_size_3XS: "16px",
  c_brandLogo_size_2XS: "20px",
  c_brandLogo_size_XS: "24px",
  c_brandLogo_size_S: "32px",
  c_brandLogo_size_M: "40px",
  c_skeleton_color_background_fade_start: "#5a657616",
  c_skeleton_color_background_fade_end: "#5a657725",
  c_skeleton_color_background_wave_base: "#5a657616",
  c_skeleton_color_background_wave_layer: "#16181d00",
  c_skeleton_color_background_none_base: "#5a657616",
  c_skeleton_color_contents_placeHolderIcon_image: "#5a657725",
  c_skeleton_color_contents_placeHolderIcon_video: "#5a657725",
  c_skeleton_duration_fade: "150ms",
  c_skeleton_duration_wave: "150ms",
  c_skeleton_radius_text: "8px",
  c_skeleton_radius_lines: "8px",
  c_skeleton_radius_thumbnail: "8px",
  c_skeleton_radius_profile: "50%",
  c_skeleton_radius_rounded: "8px",
  c_skeleton_radius_square: "0px",
  c_skeleton_radius_circle: "50%",
  c_skeleton_size_placeHolderIcon_image: "24px",
  c_skeleton_size_placeHolderIcon_video: "24px",
  c_skeleton_spacing_padding_lines: "2px 0px",
  c_charactersCounter_typography_maxLength_S:
    "500 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_charactersCounter_typography_inputLength_S:
    "500 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_charactersCounter_color_contents_inputLength_default: "#8d94a5",
  c_charactersCounter_color_contents_inputLength_vaild: "#21afbf",
  c_charactersCounter_color_contents_inputLength_invaild: "#e3371c",
  c_charactersCounter_color_contents_maxLength_default: "#8d94a5",
  c_charactersCounter_spacing_itemGap_S: "2px",
  c_inputFieldBase_typography_placeHolder_M:
    "400 0.875rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_inputFieldBase_typography_inputValue_M:
    "400 0.875rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_inputFieldBase_color_contents_placeHolder: "#70798f",
  c_inputFieldBase_color_contents_inputValue: "#16181d",
  c_inputFieldBase_spacing_padding_none_M: "0px",
  c_inputFieldBase_spacing_padding_default_M: "10px 16px",
  c_textArea_color_background_enabled_outline: "#ffffff00",
  c_textArea_color_background_enabled_backgroundOutline: "#fff",
  c_textArea_color_background_enabled_surface: "#5a657616",
  c_textArea_color_background_disabled_outline: "#5a657616",
  c_textArea_color_background_disabled_backgroundOutline: "#5a657616",
  c_textArea_color_background_disabled_surface: "#5a657616",
  c_textArea_color_border_outline_default: "#5a65773d",
  c_textArea_color_border_outline_hover: "#26C7D9",
  c_textArea_color_border_outline_focused: "#26C7D9",
  c_textArea_color_border_outline_error: "#e3371c",
  c_textArea_color_border_outline_readOnly: "#5a65773d",
  c_textArea_color_border_outline_disabled: "#5a65773d",
  c_textArea_color_border_backgroundOutline_default: "#5a65773d",
  c_textArea_color_border_backgroundOutline_hover: "#26C7D9",
  c_textArea_color_border_backgroundOutline_focused: "#26C7D9",
  c_textArea_color_border_backgroundOutline_error: "#e3371c",
  c_textArea_color_border_backgroundOutline_readOnly: "#5a65773d",
  c_textArea_color_border_backgroundOutline_disabled: "#5a65773d",
  c_textArea_color_border_surface_default: "#ffffff00",
  c_textArea_color_border_surface_hover: "#26C7D9",
  c_textArea_color_border_surface_focused: "#26C7D9",
  c_textArea_color_border_surface_error: "#e3371c",
  c_textArea_color_border_surface_readOnly: "#ffffff00",
  c_textArea_color_border_surface_disabled: "#ffffff00",
  c_textArea_borderWidth: "1px",
  c_textArea_radius_M: "8px",
  c_textArea_height_maxHeight_maxS: "120px",
  c_textArea_height_maxHeight_maxM: "160px",
  c_textArea_spacing_padding_deleteArea_M: "8px 8px 0px 0px",
  c_textArea_spacing_padding_counterArea_M: "4px 8px",
  c_textArea_opacity_disabled: "0.5",
  c_textAreaForm_spacing_itemGap_labelWithField_M: "8px",
  c_textAreaForm_spacing_itemGap_fieldWithHelptext_M: "8px",
  c_mainText_typography_S_thick:
    "600 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_mainText_typography_S_medium:
    "500 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_mainText_typography_S_thin:
    "400 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_mainText_typography_M_thick:
    "600 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_mainText_typography_M_medium:
    "500 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_mainText_typography_M_thin:
    "400 0.875rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_mainText_typography_L_thick:
    "600 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_mainText_typography_L_medium:
    "500 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_mainText_typography_L_thin:
    "400 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_mainText_color_contents_default: "#16181d",
  c_mainText_color_contents_light: "#434956",
  c_mainText_spacing_itemGap_comfortable: "8px",
  c_mainText_spacing_itemGap_compact: "4px",
  c_subText_typography_S_medium:
    "500 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_subText_typography_S_thin:
    "400 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_subText_typography_M_medium:
    "500 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_subText_typography_M_thin:
    "400 0.875rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_subText_color_contents_light: "#70798f",
  c_subText_color_contents_medium: "#434956",
  c_subText_color_contents_deep: "#16181d",
  c_commonTextGroup_spacing_itemGap_comfortable: "4px",
  c_commonTextGroup_spacing_itemGap_loose: "6px",
  c_commonTextGroup_spacing_itemGap_compact: "2px",
  c_commonTextGroup_spacing_itemGap_none: "0px",
  c_priceText_typography_price_M:
    "600 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_typography_price_L:
    "600 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_typography_price_XL:
    "600 1.25rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_typography_optionInfo_M:
    "400 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_typography_optionInfo_L:
    "400 0.875rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_typography_optionInfo_XL:
    "400 0.875rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_typography_primeCost_M:
    "400 0.75rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_typography_primeCost_L:
    "400 0.875rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_typography_primeCost_XL:
    "400 0.875rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_typography_discountPercentage_M:
    "600 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_typography_discountPercentage_L:
    "600 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_typography_discountPercentage_XL:
    "600 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  c_priceText_color_contents_price_neutral: "#16181d",
  c_priceText_color_contents_price_primary: "#21afbf",
  c_priceText_color_contents_optionInfo_neutral: "#70798f",
  c_priceText_color_contents_optionInfo_primary: "#70798f",
  c_priceText_color_contents_primeCost_neutral: "#70798f",
  c_priceText_color_contents_primeCost_primary: "#70798f",
  c_priceText_color_contents_discountPercentage_neutral: "#e3371c",
  c_priceText_color_contents_discountPercentage_primary: "#e3371c",
  c_priceText_spacing_itemGap_basic_horizontal_M: "6px",
  c_priceText_spacing_itemGap_basic_horizontal_L: "6px",
  c_priceText_spacing_itemGap_basic_horizontal_XL: "6px",
  c_priceText_spacing_itemGap_basic_vertical_M: "2px",
  c_priceText_spacing_itemGap_basic_vertical_L: "2px",
  c_priceText_spacing_itemGap_basic_vertical_XL: "2px",
  c_priceText_spacing_itemGap_discount_primeCost_horizontal_M: "6px",
  c_priceText_spacing_itemGap_discount_primeCost_horizontal_L: "6px",
  c_priceText_spacing_itemGap_discount_primeCost_horizontal_XL: "6px",
  c_priceText_spacing_itemGap_discount_primeCost_vertical_M: "0px",
  c_priceText_spacing_itemGap_discount_primeCost_vertical_L: "0px",
  c_priceText_spacing_itemGap_discount_primeCost_vertical_XL: "0px",
  c_priceText_spacing_itemGap_discount_discountPrice_horizontal_M: "6px",
  c_priceText_spacing_itemGap_discount_discountPrice_horizontal_L: "6px",
  c_priceText_spacing_itemGap_discount_discountPrice_horizontal_XL: "6px",
  c_priceText_spacing_itemGap_discount_discountPrice_vertical_M: "4px",
  c_priceText_spacing_itemGap_discount_discountPrice_vertical_L: "4px",
  c_priceText_spacing_itemGap_discount_discountPrice_vertical_XL: "4px",
  c_productInfoGroup_spacing_itemGap_basic_comfortable: "8px",
  c_thumbnailBase_color_background_surface: "#5a657616",
  c_thumbnailBase_color_background_none: "#ffffff00",
  c_thumbnailBase_color_background_background: "#fff",
  c_thumbnailBase_spacing_padding_none: "0px",
  c_thumbnailBase_spacing_padding_S: "4px",
  c_thumbnailBase_spacing_padding_M: "8px",
  c_thumbnailContainer_size_3XS: "40px",
  c_thumbnailContainer_size_2XS: "48px",
  c_thumbnailContainer_size_XS: "56px",
  c_thumbnailContainer_size_S: "64px",
  c_thumbnailContainer_size_M: "80px",
  c_thumbnailContainer_size_ML: "100px",
  c_thumbnailContainer_size_L: "120px",
  c_thumbnailContainer_size_XL: "160px",
  c_thumbnailContainer_color_border: "#5a657725",
  c_thumbnailContainer_borderWidth_borderTrue: "1px",
  c_thumbnailContainer_borderWidth_borderFalse: "0px",
  c_thumbnailContainer_radius_square_3XS: "6px",
  c_thumbnailContainer_radius_square_2XS: "6px",
  c_thumbnailContainer_radius_square_XS: "8px",
  c_thumbnailContainer_radius_square_S: "8px",
  c_thumbnailContainer_radius_square_M: "10px",
  c_thumbnailContainer_radius_square_ML: "10px",
  c_thumbnailContainer_radius_square_L: "10px",
  c_thumbnailContainer_radius_square_XL: "12px",
  c_thumbnailContainer_radius_round_default: "999px",
} as const;
