export const semanticDark = {
  s_color_brand_primary_default: "#69d0d4",
  s_color_brand_primary_light: "#35b2b7",
  s_color_brand_primary_dark: "#98dfe1",
  s_color_brand_primary_background: "#34585e",
  s_color_brand_primary_surface: "#43c4c933",
  s_color_background_default: "#2d3138",
  s_color_background_canvas: "#22252a",
  s_color_background_elevation01: "#353941",
  s_color_background_elevation02: "#414751",
  s_color_surface_lightness: "#ffffff0d",
  s_color_surface_light: "#ffffff1a",
  "s_color_surface_medium-light": "#ffffff4d",
  s_color_surface_medium: "#ffffff80",
  s_color_surface_dark: "#ffffffb3",
  s_color_surface_darkness: "#ffffffe6",
  s_color_surface_inverse_lightness: "#22252a0d",
  s_color_surface_inverse_light: "#22252a1a",
  "s_color_surface_inverse_medium-light": "#22252a4d",
  s_color_surface_inverse_medium: "#22252a80",
  s_color_surface_inverse_dark: "#22252ab3",
  s_color_surface_inverse_darkness: "#22252ae6",
  s_color_contents_default: "#fffffff2",
  s_color_contents_sub: "#ffffffcc",
  s_color_contents_additional: "#ffffff99",
  s_color_contents_weak: "#ffffff66",
  s_color_contents_disabled: "#ffffff66",
  s_color_contents_inverse_default: "#22252af2",
  s_color_contents_inverse_sub: "#22252acc",
  s_color_contents_inverse_additional: "#22252a99",
  s_color_contents_inverse_weak: "#22252a80",
  s_color_contents_inverse_disabled: "#22252a80",
  s_color_border_default: "#ffffff33",
  s_color_border_light: "#ffffff1a",
  s_color_divider_default: "#ffffff1a",
  s_color_divider_deep: "#ffffff33",
  s_color_graphic_lightness: "#ffffff33",
  s_color_graphic_light: "#ffffff4d",
  "s_color_graphic_medium-light": "#ffffff66",
  s_color_graphic_medium: "#ffffff80",
  s_color_graphic_dark: "#ffffffb3",
  s_color_graphic_darkness: "#ffffffcc",
  s_color_semantic_info_default: "#64abf7",
  s_color_semantic_info_light: "#479bf680",
  s_color_semantic_info_surface: "#479bf64d",
  s_color_semantic_info_background: "#2f4065",
  s_color_semantic_positive_default: "#5fc99e",
  s_color_semantic_positive_light: "#40bf8b80",
  s_color_semantic_positive_surface: "#40bf8b4d",
  s_color_semantic_positive_background: "#2e4f45",
  s_color_semantic_warning_default: "#ddc109",
  s_color_semantic_warning_light: "#f5d60a66",
  s_color_semantic_warning_surface: "#f5d60a26",
  s_color_semantic_warning_background: "#4d4732",
  s_color_semantic_negative_default: "#f47969",
  s_color_semantic_negative_light: "#f1574380",
  s_color_semantic_negative_surface: "#ee2e154d",
  s_color_semantic_negative_background: "#613129",
  s_color_static_black_lightness: "#0000001a",
  s_color_static_black_light: "#00000033",
  s_color_static_black_medium: "#00000080",
  s_color_static_black_dark: "#000000b3",
  s_color_static_black_darkness: "#000000e6",
  s_color_static_black_basic: "#000000",
  s_color_static_white_lightness: "#ffffff1a",
  s_color_static_white_light: "#ffffff33",
  s_color_static_white_medium: "#ffffff80",
  s_color_static_white_dark: "#ffffffb3",
  s_color_static_white_darkness: "#fffffff2",
  s_color_static_white_basic: "#ffffff",
  s_color_visualization_default_blue: "#64abf7",
  s_color_visualization_default_green: "#5fc99e",
  s_color_visualization_default_yellow: "#ddc109",
  s_color_visualization_default_orange: "#ffad5c",
  s_color_visualization_default_red: "#f47969",
  s_color_visualization_default_purple: "#c096f4",
  s_color_visualization_default_magenta: "#f87cb0",
  s_color_visualization_default_charteuse: "#B4E51A",
  s_color_visualization_light_blue: "#479bf666",
  s_color_visualization_light_green: "#40bf8b66",
  s_color_visualization_light_yellow: "#f5d60a66",
  s_color_visualization_light_orange: "#ff993366",
  s_color_visualization_light_red: "#f1574366",
  s_color_visualization_light_purple: "#b07cf166",
  s_color_visualization_light_magenta: "#f6519566",
  s_color_visualization_light_charteuse: "#b4e51a66",
  s_color_visualization_surface_blue: "#479bf633",
  s_color_visualization_surface_green: "#40bf8b33",
  s_color_visualization_surface_yellow: "#f5d60a33",
  s_color_visualization_surface_orange: "#ff993333",
  s_color_visualization_surface_red: "#ee2e154d",
  s_color_visualization_surface_purple: "#b07cf133",
  s_color_visualization_surface_magenta: "#f651954d",
  s_color_visualization_surface_charteuse: "#b4e51a26",
  s_color_visualization_background_blue: "#2f3c5a",
  s_color_visualization_background_green: "#2e4340",
  s_color_visualization_background_yellow: "#4d4732",
  s_color_visualization_background_orange: "#5d4030",
  s_color_visualization_background_red: "#55322d",
  s_color_visualization_background_purple: "#4b3a69",
  s_color_visualization_background_magenta: "#5d3442",
  s_color_visualization_background_charteuse: "#444d34",
  s_color_bizhows_default: "#4b8cf5",
  s_color_bizhows_light: "#4b8cf566",
  s_color_bizhows_surface: "#4b8cf533",
  s_color_bizhows_background: "#394663",
  s_size_button_XXS: "24px",
  s_size_button_XS: "28px",
  s_size_button_S: "32px",
  s_size_button_SM: "36px",
  s_size_button_M: "40px",
  s_size_button_ML: "44px",
  s_size_button_L: "48px",
  s_size_button_XL: "56px",
  s_size_button_XXL: "64px",
  s_radius_button_square_XXS: "6px",
  s_radius_button_square_XS: "6px",
  s_radius_button_square_S: "8px",
  s_radius_button_square_SM: "8px",
  s_radius_button_square_M: "8px",
  s_radius_button_square_ML: "8px",
  s_radius_button_square_L: "10px",
  s_radius_button_square_XL: "12px",
  s_radius_button_square_XXL: "12px",
  s_duration_button: "100ms",
  s_opacity_disabled: "0.5",
  s_opacity_interactionLayer_notFill_hover: "0.05",
  s_opacity_interactionLayer_notFill_pressed: "0.1",
  s_opacity_interactionLayer_fill_hover: "0.15",
  s_opacity_interactionLayer_fill_pressed: "0.3",
  s_opacity_stateLayer_light_hover: "0.05",
  s_opacity_stateLayer_light_pressed: "0.1",
  s_opacity_stateLayer_deep_hover: "0.15",
  s_opacity_stateLayer_deep_pressed: "0.3",
  s_typography_display_XS:
    "700 2rem/1.38 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_S:
    "700 2.5rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_M:
    "700 3rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_L:
    "700 3.5rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_XL:
    "700 4rem/1.38 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_2XL:
    "700 5rem/1.38 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_3XL:
    "700 6rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_2XS:
    "600 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_XS:
    "600 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_S:
    "600 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_M:
    "600 1.125rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_L:
    "600 1.25rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_XL:
    "600 1.5rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_2XL:
    "600 1.75rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_3XL:
    "600 2rem/1.38 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_body_S:
    "400 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_body_M:
    "400 0.875rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_body_L:
    "400 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_body_XL:
    "400 1.125rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_body_2XL:
    "400 1.25rem/1.62 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_medium_2XS:
    "500 0.625rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_medium_XS:
    "500 0.688rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_medium_S:
    "500 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_medium_M:
    "500 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_medium_L:
    "500 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_semiBold_2XS:
    "600 0.625rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_semiBold_XS:
    "600 0.688rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_semiBold_S:
    "600 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_semiBold_M:
    "600 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_semiBold_L:
    "600 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_shadow_modal: "0px 24px 64px 0 rgba(0, 0, 0, 0.2)",
  s_shadow_popup: "0px 12px 32px 0 rgba(0, 0, 0, 0.2)",
  s_shadow_popover: "0px 6px 20px 0 rgba(0, 0, 0, 0.2)",
} as const;
