export const semanticLight = {
  s_color_brand_primary_default: "#21afbf",
  s_color_brand_primary_light: "#26C7D9",
  s_color_brand_primary_dark: "#1b8b98",
  s_color_brand_primary_background: "#e9f9fb",
  s_color_brand_primary_surface: "#26c7d91a",
  s_color_background_default: "#fff",
  s_color_background_canvas: "#f1f2f4",
  s_color_background_elevation01: "#fff",
  s_color_background_elevation02: "#fff",
  s_color_surface_lightness: "#5a657616",
  s_color_surface_light: "#5a657725",
  "s_color_surface_medium-light": "#444e5c55",
  s_color_surface_medium: "#444e5c86",
  s_color_surface_dark: "#2f3640b6",
  s_color_surface_darkness: "#16181de6",
  s_color_surface_inverse_lightness: "#ffffff0d",
  s_color_surface_inverse_light: "#ffffff1a",
  "s_color_surface_inverse_medium-light": "#ffffff4d",
  s_color_surface_inverse_medium: "#ffffff80",
  s_color_surface_inverse_dark: "#ffffffb3",
  s_color_surface_inverse_darkness: "#ffffffe6",
  s_color_contents_default: "#16181d",
  s_color_contents_sub: "#434956",
  s_color_contents_additional: "#70798f",
  s_color_contents_weak: "#8d94a5",
  s_color_contents_disabled: "#8d94a5",
  s_color_contents_inverse_default: "#fffffff2",
  s_color_contents_inverse_sub: "#ffffffcc",
  s_color_contents_inverse_additional: "#ffffff80",
  s_color_contents_inverse_weak: "#ffffff66",
  s_color_contents_inverse_disabled: "#ffffff66",
  s_color_border_default: "#5a65773d",
  s_color_border_light: "#5a657725",
  s_color_divider_default: "#5a657725",
  s_color_divider_deep: "#5a65773d",
  s_color_graphic_lightness: "#5a657725",
  s_color_graphic_light: "#5a65773d",
  "s_color_graphic_medium-light": "#444e5c55",
  s_color_graphic_medium: "#444e5c86",
  s_color_graphic_dark: "#2f3640b6",
  s_color_graphic_darkness: "#16181dcc",
  s_color_semantic_info_default: "#1A7BE5",
  s_color_semantic_info_light: "#1a7be566",
  s_color_semantic_info_surface: "#1a7be51a",
  s_color_semantic_info_background: "#e8f2fc",
  s_color_semantic_positive_default: "#40BF8B",
  s_color_semantic_positive_light: "#40bf8b66",
  s_color_semantic_positive_surface: "#40bf8b1a",
  s_color_semantic_positive_background: "#ecf9f3",
  s_color_semantic_warning_default: "#F5D70A",
  s_color_semantic_warning_light: "#f5d70a66",
  s_color_semantic_warning_surface: "#f5d70a1a",
  s_color_semantic_warning_background: "#fefbe6",
  s_color_semantic_negative_default: "#e3371c",
  s_color_semantic_negative_light: "#e3371c66",
  s_color_semantic_negative_surface: "#e3371c1a",
  s_color_semantic_negative_background: "#fcebe8",
  s_color_static_black_lightness: "#0000001a",
  s_color_static_black_light: "#00000033",
  s_color_static_black_medium: "#00000080",
  s_color_static_black_dark: "#000000b3",
  s_color_static_black_darkness: "#000000e6",
  s_color_static_black_basic: "#000000",
  s_color_static_white_lightness: "#ffffff1a",
  s_color_static_white_light: "#ffffff33",
  s_color_static_white_medium: "#ffffff80",
  s_color_static_white_dark: "#ffffffb3",
  s_color_static_white_darkness: "#ffffffe6",
  s_color_static_white_basic: "#ffffff",
  s_color_visualization_default_blue: "#1A7BE5",
  s_color_visualization_default_green: "#40BF8B",
  s_color_visualization_default_yellow: "#F5D70A",
  s_color_visualization_default_orange: "#f8820d",
  s_color_visualization_default_red: "#e3371c",
  s_color_visualization_default_purple: "#935cd6",
  s_color_visualization_default_magenta: "#e54d8d",
  s_color_visualization_default_charteuse: "#aed629",
  s_color_visualization_light_blue: "#1a7be566",
  s_color_visualization_light_green: "#40bf8b66",
  s_color_visualization_light_yellow: "#f5d70a66",
  s_color_visualization_light_orange: "#f8820d66",
  s_color_visualization_light_red: "#e3371c66",
  s_color_visualization_light_purple: "#935cd666",
  s_color_visualization_light_magenta: "#e54d8d66",
  s_color_visualization_light_charteuse: "#aed62966",
  s_color_visualization_surface_blue: "#1a7be51a",
  s_color_visualization_surface_green: "#40bf8b1a",
  s_color_visualization_surface_yellow: "#f5d70a1a",
  s_color_visualization_surface_orange: "#f8820d1a",
  s_color_visualization_surface_red: "#e3371c1a",
  s_color_visualization_surface_purple: "#7833cc1a",
  s_color_visualization_surface_magenta: "#df20701a",
  s_color_visualization_surface_charteuse: "#aed6291a",
  s_color_visualization_background_blue: "#e8f2fc",
  s_color_visualization_background_green: "#ecf9f3",
  s_color_visualization_background_yellow: "#fefbe6",
  s_color_visualization_background_orange: "#fef3e7",
  s_color_visualization_background_red: "#fcebe8",
  s_color_visualization_background_purple: "#f2ebfa",
  s_color_visualization_background_magenta: "#fce9f1",
  s_color_visualization_background_charteuse: "#f7fbea",
  s_color_bizhows_default: "#4286F4",
  s_color_bizhows_light: "#4286f466",
  s_color_bizhows_background: "#ecf3fe",
  s_color_bizhows_surface: "#4286f41a",
  s_size_button_XXS: "24px",
  s_size_button_XS: "28px",
  s_size_button_S: "32px",
  s_size_button_SM: "36px",
  s_size_button_M: "40px",
  s_size_button_ML: "44px",
  s_size_button_L: "48px",
  s_size_button_XL: "56px",
  s_size_button_XXL: "64px",
  s_radius_button_square_XXS: "6px",
  s_radius_button_square_XS: "6px",
  s_radius_button_square_S: "8px",
  s_radius_button_square_SM: "8px",
  s_radius_button_square_M: "8px",
  s_radius_button_square_ML: "8px",
  s_radius_button_square_L: "10px",
  s_radius_button_square_XL: "12px",
  s_radius_button_square_XXL: "12px",
  s_duration_button: "100ms",
  s_opacity_disabled: "0.5",
  s_opacity_interactionLayer_notFill_hover: "0.05",
  s_opacity_interactionLayer_notFill_pressed: "0.1",
  s_opacity_interactionLayer_fill_hover: "0.15",
  s_opacity_interactionLayer_fill_pressed: "0.3",
  s_opacity_stateLayer_light_hover: "0.05",
  s_opacity_stateLayer_light_pressed: "0.1",
  s_opacity_stateLayer_deep_hover: "0.15",
  s_opacity_stateLayer_deep_pressed: "0.3",
  s_typography_display_XS:
    "700 2rem/1.38 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_S:
    "700 2.5rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_M:
    "700 3rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_L:
    "700 3.5rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_XL:
    "700 4rem/1.38 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_2XL:
    "700 5rem/1.38 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_display_3XL:
    "700 6rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_2XS:
    "600 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_XS:
    "600 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_S:
    "600 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_M:
    "600 1.125rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_L:
    "600 1.25rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_XL:
    "600 1.5rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_2XL:
    "600 1.75rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_title_3XL:
    "600 2rem/1.38 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_body_S:
    "400 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_body_M:
    "400 0.875rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_body_L:
    "400 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_body_XL:
    "400 1.125rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_body_2XL:
    "400 1.25rem/1.62 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_medium_2XS:
    "500 0.625rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_medium_XS:
    "500 0.688rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_medium_S:
    "500 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_medium_M:
    "500 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_medium_L:
    "500 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_semiBold_2XS:
    "600 0.625rem/1.42 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_semiBold_XS:
    "600 0.688rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_semiBold_S:
    "600 0.75rem/1.35 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_semiBold_M:
    "600 0.875rem/1.46 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_typography_label_semiBold_L:
    "600 1rem/1.53 'Pretendard Variable', Figtree, 'IBM Plex Sans JP'",
  s_shadow_modal: "0px 24px 64px 0 rgba(0, 0, 0, 0.2)",
  s_shadow_popup: "0px 12px 32px 0 rgba(0, 0, 0, 0.2)",
  s_shadow_popover: "0px 6px 20px 0 rgba(0, 0, 0, 0.2)",
} as const;
