import { token } from "@cpdev2/primitive";

export const baseSpacing = {
  "0": token(`b_spacing_0`),
  "10": token(`b_spacing_10`),
  "20": token(`b_spacing_20`),
  "30": token(`b_spacing_30`),
  "40": token(`b_spacing_40`),
  "50": token(`b_spacing_50`),
  "60": token(`b_spacing_60`),
  "70": token(`b_spacing_70`),
  "80": token(`b_spacing_80`),
  "90": token(`b_spacing_90`),
  "100": token(`b_spacing_100`),
  "110": token(`b_spacing_110`),
  "120": token(`b_spacing_120`),
  "130": token(`b_spacing_130`),
  "140": token(`b_spacing_140`),
  "150": token(`b_spacing_150`),
  "160": token(`b_spacing_160`),
} as const;

export const baseSize = {
  static_10: token(`b_size_static_10`),
  static_20: token(`b_size_static_20`),
  static_30: token(`b_size_static_30`),
  static_40: token(`b_size_static_40`),
  static_50: token(`b_size_static_50`),
  static_60: token(`b_size_static_60`),
  static_70: token(`b_size_static_70`),
  static_80: token(`b_size_static_80`),
  static_90: token(`b_size_static_90`),
  static_100: token(`b_size_static_100`),
  static_110: token(`b_size_static_110`),
  static_120: token(`b_size_static_120`),
  static_130: token(`b_size_static_130`),
  static_140: token(`b_size_static_140`),
  static_150: token(`b_size_static_150`),
  static_160: token(`b_size_static_160`),
  static_170: token(`b_size_static_170`),
  static_180: token(`b_size_static_180`),
  static_190: token(`b_size_static_190`),
  static_200: token(`b_size_static_200`),
  static_210: token(`b_size_static_210`),
} as const;

export const baseRadius = {
  "0": token(`b_radius_0`),
  "10": token(`b_radius_10`),
  "20": token(`b_radius_20`),
  "30": token(`b_radius_30`),
  "40": token(`b_radius_40`),
  "50": token(`b_radius_50`),
  "60": token(`b_radius_60`),
  "70": token(`b_radius_70`),
  "80": token(`b_radius_80`),
  "90": token(`b_radius_90`),
  "100": token(`b_radius_100`),
  pill: token(`b_radius_pill`),
  circle: token(`b_radius_circle`),
} as const;

export const baseTypography = {
  body_S: token(`b_typography_body_S`),
  body_M: token(`b_typography_body_M`),
  body_L: token(`b_typography_body_L`),
  body_XL: token(`b_typography_body_XL`),
  body_2XL: token(`b_typography_body_2XL`),
  label_medium_2XS: token(`s_typography_label_medium_2XS`),
  label_medium_XS: token(`s_typography_label_medium_XS`),
  label_medium_S: token(`s_typography_label_medium_S`),
  label_medium_M: token(`s_typography_label_medium_M`),
  label_medium_L: token(`s_typography_label_medium_L`),
  semiBold_2XS: token(`s_typography_label_semiBold_2XS`),
  semiBold_XS: token(`s_typography_label_semiBold_XS`),
  semiBold_S: token(`s_typography_label_semiBold_S`),
  semiBold_M: token(`s_typography_label_semiBold_M`),
  semiBold_L: token(`s_typography_label_semiBold_L`),
  title_2XS: token(`s_typography_title_2XS`),
  title_XS: token(`s_typography_title_XS`),
  title_S: token(`s_typography_title_S`),
  title_M: token(`s_typography_title_M`),
  title_L: token(`s_typography_title_L`),
  title_XL: token(`s_typography_title_XL`),
  title_2XL: token(`s_typography_title_2XL`),
  display_XS: token(`s_typography_display_XS`),
  display_S: token(`s_typography_display_S`),
  display_M: token(`s_typography_display_M`),
  display_L: token(`s_typography_display_L`),
  display_XL: token(`s_typography_display_XL`),
  display_2XL: token(`s_typography_display_2XL`),
} as const;

export const colorStatic = {
  black_lightness: token(`s_color_static_black_lightness`),
  black_light: token(`s_color_static_black_light`),
  black_medium: token(`s_color_static_black_medium`),
  black_dark: token(`s_color_static_black_dark`),
  black_darkness: token(`s_color_static_black_darkness`),
  black_basic: token(`s_color_static_black_basic`),
  white_lightness: token(`s_color_static_white_lightness`),
  white_light: token(`s_color_static_white_light`),
  white_medium: token(`s_color_static_white_medium`),
  white_dark: token(`s_color_static_white_dark`),
  white_darkness: token(`s_color_static_white_darkness`),
  white_basic: token(`s_color_static_white_basic`),
} as const;

export const semanticContentsColor = {
  contents_default: token(`s_color_contents_default`),
  contents_sub: token(`s_color_contents_sub`),
  contents_additional: token(`s_color_contents_additional`),
  contents_weak: token(`s_color_contents_weak`),
  contents_disabled: token(`s_color_contents_disabled`),
  inverse_default: token(`s_color_contents_inverse_default`),
  inverse_sub: token(`s_color_contents_inverse_sub`),
  inverse_additional: token(`s_color_contents_inverse_additional`),
  inverse_weak: token(`s_color_contents_inverse_weak`),
  inverse_disabled: token(`s_color_contents_inverse_disabled`),
} as const;

export const semantic = {
  semantic_info_default: token(`s_color_semantic_info_default`),
  semantic_info_light: token(`s_color_semantic_info_light`),
  semantic_info_surface: token(`s_color_semantic_info_surface`),
  semantic_info_background: token(`s_color_semantic_info_background`),
  semantic_positive_default: token(`s_color_semantic_positive_default`),
  semantic_positive_light: token(`s_color_semantic_positive_light`),
  semantic_positive_surface: token(`s_color_semantic_positive_surface`),
  semantic_positive_background: token(`s_color_semantic_positive_background`),
  semantic_warning_default: token(`s_color_semantic_warning_default`),
  semantic_warning_light: token(`s_color_semantic_warning_light`),
  semantic_warning_surface: token(`s_color_semantic_warning_surface`),
  semantic_warning_background: token(`s_color_semantic_warning_background`),
  semantic_negative_default: token(`s_color_semantic_negative_default`),
  semantic_negative_light: token(`s_color_semantic_negative_light`),
  semantic_negative_surface: token(`s_color_semantic_negative_surface`),
  semantic_negative_background: token(`s_color_semantic_negative_background`),
} as const;
