import { token } from "@cpdev2/primitive";

export const baseSpacing = {
  "0": token(`b_spacing_0`),
  "10": token(`b_spacing_10`),
  "20": token(`b_spacing_20`),
  "30": token(`b_spacing_30`),
  "40": token(`b_spacing_40`),
  "50": token(`b_spacing_50`),
  "60": token(`b_spacing_60`),
  "70": token(`b_spacing_70`),
  "80": token(`b_spacing_80`),
  "90": token(`b_spacing_90`),
  "100": token(`b_spacing_100`),
  "110": token(`b_spacing_110`),
  "120": token(`b_spacing_120`),
  "130": token(`b_spacing_130`),
  "140": token(`b_spacing_140`),
  "150": token(`b_spacing_150`),
  "160": token(`b_spacing_160`),
} as const;

export const baseTypography = {
  body_S: token(`b_typography_body_S`),
  body_M: token(`b_typography_body_M`),
  body_L: token(`b_typography_body_L`),
  body_XL: token(`b_typography_body_XL`),
  body_2XL: token(`b_typography_body_2XL`),
  label_medium_2XS: token(`s_typography_label_medium_2XS`),
  label_medium_XS: token(`s_typography_label_medium_XS`),
  label_medium_S: token(`s_typography_label_medium_S`),
  label_medium_M: token(`s_typography_label_medium_M`),
  label_medium_L: token(`s_typography_label_medium_L`),
  semiBold_2XS: token(`s_typography_label_semiBold_2XS`),
  semiBold_XS: token(`s_typography_label_semiBold_XS`),
  semiBold_S: token(`s_typography_label_semiBold_S`),
  semiBold_M: token(`s_typography_label_semiBold_M`),
  semiBold_L: token(`s_typography_label_semiBold_L`),
  title_2XS: token(`s_typography_title_2XS`),
  title_XS: token(`s_typography_title_XS`),
  title_S: token(`s_typography_title_S`),
  title_M: token(`s_typography_title_M`),
  title_L: token(`s_typography_title_L`),
  title_XL: token(`s_typography_title_XL`),
  title_2XL: token(`s_typography_title_2XL`),
  display_XS: token(`s_typography_display_XS`),
  display_S: token(`s_typography_display_S`),
  display_M: token(`s_typography_display_M`),
  display_L: token(`s_typography_display_L`),
  display_XL: token(`s_typography_display_XL`),
  display_2XL: token(`s_typography_display_2XL`),
} as const;

export const semanticContentsColor = {
  contents_default: token(`s_color_contents_default`),
  contents_sub: token(`s_color_contents_sub`),
  contents_additional: token(`s_color_contents_additional`),
  contents_weak: token(`s_color_contents_weak`),
  contents_disabled: token(`s_color_contents_disabled`),
  inverse_default: token(`s_color_contents_inverse_default`),
  inverse_sub: token(`s_color_contents_inverse_sub`),
  inverse_additional: token(`s_color_contents_inverse_additional`),
  inverse_weak: token(`s_color_contents_inverse_weak`),
  inverse_disabled: token(`s_color_contents_inverse_disabled`),
} as const;

export const semantic = {
  semantic_info_default: token(`s_color_semantic_info_default`),
  semantic_info_light: token(`s_color_semantic_info_light`),
  semantic_info_surface: token(`s_color_semantic_info_surface`),
  semantic_info_background: token(`s_color_semantic_info_background`),
  semantic_positive_default: token(`s_color_semantic_positive_default`),
  semantic_positive_light: token(`s_color_semantic_positive_light`),
  semantic_positive_surface: token(`s_color_semantic_positive_surface`),
  semantic_positive_background: token(`s_color_semantic_positive_background`),
  semantic_warning_default: token(`s_color_semantic_warning_default`),
  semantic_warning_light: token(`s_color_semantic_warning_light`),
  semantic_warning_surface: token(`s_color_semantic_warning_surface`),
  semantic_warning_background: token(`s_color_semantic_warning_background`),
  semantic_negative_default: token(`s_color_semantic_negative_default`),
  semantic_negative_light: token(`s_color_semantic_negative_light`),
  semantic_negative_surface: token(`s_color_semantic_negative_surface`),
  semantic_negative_background: token(`s_color_semantic_negative_background`),
} as const;
